#!/usr/bin/env node

const commander = require('commander'); // (normal include)
// const commander = require('./index.js'); // include commander in git clone of commander repo
const program = new commander.Command();
const version = require('./package.json').version;

program
    .name('index.js')
    .description('Run postman collection(s) with the specified options')
    .version(version, '-f, --version')
    .addHelpCommand(true)
    .requiredOption('-k --keyDescriptor <keyDescriptor>', 'Postman Collection Description Json \n' +
        'Format is: \n' +
        '\t{\n' +
        '\t\t"collections"\t: [\n' +
        '\t\t{\n' +
        '\t\t"collection"\t:\t"collections/samplerest.postman_collection.json"\n' +
        '\t\t"environment"\t:\t"environments/sample.postman_environment.json"\n' +
        '\t\t"datafile"\t:\t"datafiles/datafile.csv"\n' +
        '\t\t"iterationCount"\t:\t"all"\n' +
        '\t\t"delayRequest"\t:\t0\n' +
        '\t\t"reportFile"\t:\t"sampleRestWithData"\n' +
        '\t\t"reportTitle"\t:\t"Sample Rest Collection"\n' +
        '\t\t}\n' +
        '\t]}\n');

program.parse(process.argv);
const options = program.opts();

module.exports = exports = program;

